# GitHub Action
# MSI-B360-Catalina-EFI

name: Upload EFI to release

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Packaging EFI
        run: |
          zip -q -r AMD.RX550Lexa+IGPU.iMac19.1.zip ./AMD\ 5500XT+IGPU\ \(iMac19\,1\)
          zip -q -r AMD.5500XT+IGPU.iMac19.1.zip ./AMD\ 5500XT+IGPU\ \(iMac19\,1\)
          zip -q -r AMD.5700XT+IGPU.iMac19.1.zip ./AMD\ 5700XT+IGPU\ \(iMac19\,1\)
          zip -q -r AMD.GPU+IGPU.iMac19.1.zip ./AMD\ GPU+IGPU\ \(iMac19\,1\)
          zip -q -r ONLY.AMD.GPU.iMacPro1.1.zip ./ONLY\ AMD\ GPU\ \(iMacPro1\,1\)
          zip -q -r ONLY.IGPU.Macmini8.1.zip ./ONLY\ IGPU\ \(Macmini8\,1\)
          ls -l *.zip

      - name: Generate release tag
        id: tag
        run: |
          chmod +x .github/workflows/update-changelog.sh
          bash .github/workflows/update-changelog.sh
          echo "::set-output name=release_tag::$(cat ReleaseTag)"
          cat ReleaseTag

      - name: Upload EFI to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: MSI-B360-${{ steps.tag.outputs.release_tag }}-EFI
          tag_name: ${{ steps.tag.outputs.release_tag }}
          prerelease: false
          body_path: Changelog.md
          files: |
            ./*.zip
